/// <reference types="nativewind/types" />

/*
 * And Expo's own types, referenced here rather than left to expo-env.d.ts.
 *
 * That file is generated by running Expo and is in .gitignore, so on this
 * machine it exists and the typecheck passes, while a fresh clone — which is
 * what CI is — has no declaration for `import '../../global.css'` and the
 * typecheck fails on the first line of the root layout. This file is ours and
 * is committed, so referencing it here makes the check mean the same thing
 * everywhere.
 */
/// <reference types="expo/types" />
