/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoundationsRouteImport } from './routes/foundations'
import { Route as ModalsRouteImport } from './routes/modals'
import { Route as PhoneRouteImport } from './routes/phone'
import { Route as ScreensRouteImport } from './routes/screens'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsRoute = FoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalsRoute = ModalsRouteImport.update({
  id: '/modals',
  path: '/modals',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRoute = PhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/foundations': typeof FoundationsRoute
  '/modals': typeof ModalsRoute
  '/phone': typeof PhoneRoute
  '/screens': typeof ScreensRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/foundations': typeof FoundationsRoute
  '/modals': typeof ModalsRoute
  '/phone': typeof PhoneRoute
  '/screens': typeof ScreensRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/foundations': typeof FoundationsRoute
  '/modals': typeof ModalsRoute
  '/phone': typeof PhoneRoute
  '/screens': typeof ScreensRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/foundations' | '/modals' | '/phone' | '/screens'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/foundations' | '/modals' | '/phone' | '/screens'
  id: '__root__' | '/' | '/foundations' | '/modals' | '/phone' | '/screens'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FoundationsRoute: typeof FoundationsRoute
  ModalsRoute: typeof ModalsRoute
  PhoneRoute: typeof PhoneRoute
  ScreensRoute: typeof ScreensRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations': {
      id: '/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof FoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modals': {
      id: '/modals'
      path: '/modals'
      fullPath: '/modals'
      preLoaderRoute: typeof ModalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone': {
      id: '/phone'
      path: '/phone'
      fullPath: '/phone'
      preLoaderRoute: typeof PhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FoundationsRoute: FoundationsRoute,
  ModalsRoute: ModalsRoute,
  PhoneRoute: PhoneRoute,
  ScreensRoute: ScreensRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
