/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as JoinRouteImport } from './routes/join'
import { Route as KitRouteImport } from './routes/kit'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetRouteImport } from './routes/reset'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppBankRouteImport } from './routes/_app/bank'
import { Route as AppCompareRouteImport } from './routes/_app/compare'
import { Route as AppCostsRouteImport } from './routes/_app/costs'
import { Route as AppGigsRouteImport } from './routes/_app/gigs'
import { Route as AppPayoutsRouteImport } from './routes/_app/payouts'
import { Route as AppPayslipRouteImport } from './routes/_app/payslip'
import { Route as AppPlacesRouteImport } from './routes/_app/places'
import { Route as AppReportRouteImport } from './routes/_app/report'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppSeekersRouteImport } from './routes/_app/seekers'
import { Route as AppServiceRouteImport } from './routes/_app/service'
import { Route as AppShiftsRouteImport } from './routes/_app/shifts'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppWrappedRouteImport } from './routes/_app/wrapped'
import { Route as KitIndexRouteImport } from './routes/kit/index'
import { Route as KitModalsRouteImport } from './routes/kit/modals'
import { Route as KitPhoneRouteImport } from './routes/kit/phone'
import { Route as KitStatesRouteImport } from './routes/kit/states'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const KitRoute = KitRouteImport.update({
  id: '/kit',
  path: '/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRoute = ResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppCompareRoute = AppCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => AppRoute,
} as any)
const AppCostsRoute = AppCostsRouteImport.update({
  id: '/costs',
  path: '/costs',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsRoute = AppGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoutsRoute = AppPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppPayslipRoute = AppPayslipRouteImport.update({
  id: '/payslip',
  path: '/payslip',
  getParentRoute: () => AppRoute,
} as any)
const AppPlacesRoute = AppPlacesRouteImport.update({
  id: '/places',
  path: '/places',
  getParentRoute: () => AppRoute,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppSeekersRoute = AppSeekersRouteImport.update({
  id: '/seekers',
  path: '/seekers',
  getParentRoute: () => AppRoute,
} as any)
const AppServiceRoute = AppServiceRouteImport.update({
  id: '/service',
  path: '/service',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppWrappedRoute = AppWrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => AppRoute,
} as any)
const KitIndexRoute = KitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KitRoute,
} as any)
const KitModalsRoute = KitModalsRouteImport.update({
  id: '/modals',
  path: '/modals',
  getParentRoute: () => KitRoute,
} as any)
const KitPhoneRoute = KitPhoneRouteImport.update({
  id: '/phone',
  path: '/phone',
  getParentRoute: () => KitRoute,
} as any)
const KitStatesRoute = KitStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => KitRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/join': typeof JoinRoute
  '/kit': typeof KitRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/account': typeof AppAccountRoute
  '/bank': typeof AppBankRoute
  '/compare': typeof AppCompareRoute
  '/costs': typeof AppCostsRoute
  '/gigs': typeof AppGigsRoute
  '/payouts': typeof AppPayoutsRoute
  '/payslip': typeof AppPayslipRoute
  '/places': typeof AppPlacesRoute
  '/report': typeof AppReportRoute
  '/schedule': typeof AppScheduleRoute
  '/seekers': typeof AppSeekersRoute
  '/service': typeof AppServiceRoute
  '/shifts': typeof AppShiftsRoute
  '/stats': typeof AppStatsRoute
  '/team': typeof AppTeamRoute
  '/wrapped': typeof AppWrappedRoute
  '/kit/modals': typeof KitModalsRoute
  '/kit/phone': typeof KitPhoneRoute
  '/kit/states': typeof KitStatesRoute
  '/kit/': typeof KitIndexRoute
}
export interface FileRoutesByTo {
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/account': typeof AppAccountRoute
  '/bank': typeof AppBankRoute
  '/compare': typeof AppCompareRoute
  '/costs': typeof AppCostsRoute
  '/gigs': typeof AppGigsRoute
  '/payouts': typeof AppPayoutsRoute
  '/payslip': typeof AppPayslipRoute
  '/places': typeof AppPlacesRoute
  '/report': typeof AppReportRoute
  '/schedule': typeof AppScheduleRoute
  '/seekers': typeof AppSeekersRoute
  '/service': typeof AppServiceRoute
  '/shifts': typeof AppShiftsRoute
  '/stats': typeof AppStatsRoute
  '/team': typeof AppTeamRoute
  '/wrapped': typeof AppWrappedRoute
  '/kit/modals': typeof KitModalsRoute
  '/kit/phone': typeof KitPhoneRoute
  '/kit/states': typeof KitStatesRoute
  '/': typeof AppIndexRoute
  '/kit': typeof KitIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/join': typeof JoinRoute
  '/kit': typeof KitRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset': typeof ResetRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/bank': typeof AppBankRoute
  '/_app/compare': typeof AppCompareRoute
  '/_app/costs': typeof AppCostsRoute
  '/_app/gigs': typeof AppGigsRoute
  '/_app/payouts': typeof AppPayoutsRoute
  '/_app/payslip': typeof AppPayslipRoute
  '/_app/places': typeof AppPlacesRoute
  '/_app/report': typeof AppReportRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/seekers': typeof AppSeekersRoute
  '/_app/service': typeof AppServiceRoute
  '/_app/shifts': typeof AppShiftsRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/wrapped': typeof AppWrappedRoute
  '/kit/modals': typeof KitModalsRoute
  '/kit/phone': typeof KitPhoneRoute
  '/kit/states': typeof KitStatesRoute
  '/_app/': typeof AppIndexRoute
  '/kit/': typeof KitIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/join'
    | '/kit'
    | '/login'
    | '/register'
    | '/reset'
    | '/account'
    | '/bank'
    | '/compare'
    | '/costs'
    | '/gigs'
    | '/payouts'
    | '/payslip'
    | '/places'
    | '/report'
    | '/schedule'
    | '/seekers'
    | '/service'
    | '/shifts'
    | '/stats'
    | '/team'
    | '/wrapped'
    | '/kit/modals'
    | '/kit/phone'
    | '/kit/states'
    | '/kit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/join'
    | '/login'
    | '/register'
    | '/reset'
    | '/account'
    | '/bank'
    | '/compare'
    | '/costs'
    | '/gigs'
    | '/payouts'
    | '/payslip'
    | '/places'
    | '/report'
    | '/schedule'
    | '/seekers'
    | '/service'
    | '/shifts'
    | '/stats'
    | '/team'
    | '/wrapped'
    | '/kit/modals'
    | '/kit/phone'
    | '/kit/states'
    | '/'
    | '/kit'
  id:
    | '__root__'
    | '/_app'
    | '/join'
    | '/kit'
    | '/login'
    | '/register'
    | '/reset'
    | '/_app/account'
    | '/_app/bank'
    | '/_app/compare'
    | '/_app/costs'
    | '/_app/gigs'
    | '/_app/payouts'
    | '/_app/payslip'
    | '/_app/places'
    | '/_app/report'
    | '/_app/schedule'
    | '/_app/seekers'
    | '/_app/service'
    | '/_app/shifts'
    | '/_app/stats'
    | '/_app/team'
    | '/_app/wrapped'
    | '/kit/modals'
    | '/kit/phone'
    | '/kit/states'
    | '/_app/'
    | '/kit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  JoinRoute: typeof JoinRoute
  KitRoute: typeof KitRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetRoute: typeof ResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kit': {
      id: '/kit'
      path: '/kit'
      fullPath: '/kit'
      preLoaderRoute: typeof KitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset': {
      id: '/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof ResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank': {
      id: '/_app/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compare': {
      id: '/_app/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof AppCompareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/costs': {
      id: '/_app/costs'
      path: '/costs'
      fullPath: '/costs'
      preLoaderRoute: typeof AppCostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs': {
      id: '/_app/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof AppGigsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payouts': {
      id: '/_app/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AppPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payslip': {
      id: '/_app/payslip'
      path: '/payslip'
      fullPath: '/payslip'
      preLoaderRoute: typeof AppPayslipRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/places': {
      id: '/_app/places'
      path: '/places'
      fullPath: '/places'
      preLoaderRoute: typeof AppPlacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seekers': {
      id: '/_app/seekers'
      path: '/seekers'
      fullPath: '/seekers'
      preLoaderRoute: typeof AppSeekersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/service': {
      id: '/_app/service'
      path: '/service'
      fullPath: '/service'
      preLoaderRoute: typeof AppServiceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shifts': {
      id: '/_app/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wrapped': {
      id: '/_app/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof AppWrappedRouteImport
      parentRoute: typeof AppRoute
    }
    '/kit/': {
      id: '/kit/'
      path: '/'
      fullPath: '/kit/'
      preLoaderRoute: typeof KitIndexRouteImport
      parentRoute: typeof KitRoute
    }
    '/kit/modals': {
      id: '/kit/modals'
      path: '/modals'
      fullPath: '/kit/modals'
      preLoaderRoute: typeof KitModalsRouteImport
      parentRoute: typeof KitRoute
    }
    '/kit/phone': {
      id: '/kit/phone'
      path: '/phone'
      fullPath: '/kit/phone'
      preLoaderRoute: typeof KitPhoneRouteImport
      parentRoute: typeof KitRoute
    }
    '/kit/states': {
      id: '/kit/states'
      path: '/states'
      fullPath: '/kit/states'
      preLoaderRoute: typeof KitStatesRouteImport
      parentRoute: typeof KitRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppBankRoute: typeof AppBankRoute
  AppCompareRoute: typeof AppCompareRoute
  AppCostsRoute: typeof AppCostsRoute
  AppGigsRoute: typeof AppGigsRoute
  AppPayoutsRoute: typeof AppPayoutsRoute
  AppPayslipRoute: typeof AppPayslipRoute
  AppPlacesRoute: typeof AppPlacesRoute
  AppReportRoute: typeof AppReportRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSeekersRoute: typeof AppSeekersRoute
  AppServiceRoute: typeof AppServiceRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppStatsRoute: typeof AppStatsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppWrappedRoute: typeof AppWrappedRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppBankRoute: AppBankRoute,
  AppCompareRoute: AppCompareRoute,
  AppCostsRoute: AppCostsRoute,
  AppGigsRoute: AppGigsRoute,
  AppPayoutsRoute: AppPayoutsRoute,
  AppPayslipRoute: AppPayslipRoute,
  AppPlacesRoute: AppPlacesRoute,
  AppReportRoute: AppReportRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSeekersRoute: AppSeekersRoute,
  AppServiceRoute: AppServiceRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppStatsRoute: AppStatsRoute,
  AppTeamRoute: AppTeamRoute,
  AppWrappedRoute: AppWrappedRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface KitRouteChildren {
  KitModalsRoute: typeof KitModalsRoute
  KitPhoneRoute: typeof KitPhoneRoute
  KitStatesRoute: typeof KitStatesRoute
  KitIndexRoute: typeof KitIndexRoute
}

const KitRouteChildren: KitRouteChildren = {
  KitModalsRoute: KitModalsRoute,
  KitPhoneRoute: KitPhoneRoute,
  KitStatesRoute: KitStatesRoute,
  KitIndexRoute: KitIndexRoute,
}

const KitRouteWithChildren = KitRoute._addFileChildren(KitRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  JoinRoute: JoinRoute,
  KitRoute: KitRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetRoute: ResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
