/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppBankRouteImport } from './routes/_app/bank'
import { Route as AppGigsRouteImport } from './routes/_app/gigs'
import { Route as AppPayoutsRouteImport } from './routes/_app/payouts'
import { Route as AppScheduleRouteImport } from './routes/_app/schedule'
import { Route as AppStatsRouteImport } from './routes/_app/stats'
import { Route as AppWrappedRouteImport } from './routes/_app/wrapped'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppBankRoute = AppBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AppRoute,
} as any)
const AppGigsRoute = AppGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoutsRoute = AppPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppWrappedRoute = AppWrappedRouteImport.update({
  id: '/wrapped',
  path: '/wrapped',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/sign-in': typeof SignInRoute
  '/account': typeof AppAccountRoute
  '/bank': typeof AppBankRoute
  '/gigs': typeof AppGigsRoute
  '/payouts': typeof AppPayoutsRoute
  '/schedule': typeof AppScheduleRoute
  '/stats': typeof AppStatsRoute
  '/wrapped': typeof AppWrappedRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof SignInRoute
  '/account': typeof AppAccountRoute
  '/bank': typeof AppBankRoute
  '/gigs': typeof AppGigsRoute
  '/payouts': typeof AppPayoutsRoute
  '/schedule': typeof AppScheduleRoute
  '/stats': typeof AppStatsRoute
  '/wrapped': typeof AppWrappedRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/bank': typeof AppBankRoute
  '/_app/gigs': typeof AppGigsRoute
  '/_app/payouts': typeof AppPayoutsRoute
  '/_app/schedule': typeof AppScheduleRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/wrapped': typeof AppWrappedRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/account'
    | '/bank'
    | '/gigs'
    | '/payouts'
    | '/schedule'
    | '/stats'
    | '/wrapped'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/account'
    | '/bank'
    | '/gigs'
    | '/payouts'
    | '/schedule'
    | '/stats'
    | '/wrapped'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/sign-in'
    | '/_app/account'
    | '/_app/bank'
    | '/_app/gigs'
    | '/_app/payouts'
    | '/_app/schedule'
    | '/_app/stats'
    | '/_app/wrapped'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bank': {
      id: '/_app/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AppBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/gigs': {
      id: '/_app/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof AppGigsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payouts': {
      id: '/_app/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AppPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/schedule': {
      id: '/_app/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wrapped': {
      id: '/_app/wrapped'
      path: '/wrapped'
      fullPath: '/wrapped'
      preLoaderRoute: typeof AppWrappedRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppBankRoute: typeof AppBankRoute
  AppGigsRoute: typeof AppGigsRoute
  AppPayoutsRoute: typeof AppPayoutsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppStatsRoute: typeof AppStatsRoute
  AppWrappedRoute: typeof AppWrappedRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppBankRoute: AppBankRoute,
  AppGigsRoute: AppGigsRoute,
  AppPayoutsRoute: AppPayoutsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppStatsRoute: AppStatsRoute,
  AppWrappedRoute: AppWrappedRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
