import { chromium } from '@playwright/test';
const API = 'http://localhost:5208/shifter/v1';
const login = 'gg-' + Date.now().toString(36);
const reg = await fetch(`${API}/auth/user/register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ login, password: 'e2e-password-12345', first_name: 'Аня', last_name: 'Проба' }) });
const session = await reg.json();
const shot = '/private/tmp/claude-501/-Users-abooser-Documents-repos-Shifter/594825d7-ad3e-4f83-8b27-d2f1105ca36d/scratchpad';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1440, height: 950 } });
p.on('console', (m) => m.type() === 'error' && console.log('CONSOLE', m.text().slice(0, 160)));
await p.addInitScript((s) => localStorage.setItem('shifter.session', JSON.stringify(s)), session);
await p.goto('http://localhost:5210/gigs');
await p.waitForTimeout(2600);
console.log('ALL     ', (await p.locator('main').innerText()).replace(/\n/g, ' | ').slice(0, 240));
await p.screenshot({ path: `${shot}/gigs.png` });
await p.getByRole('button', { name: 'постоянные' }).click();
await p.waitForTimeout(1800);
console.log('PERM    ', (await p.locator('main').innerText()).replace(/\n/g, ' | ').slice(0, 200));
await p.getByRole('button', { name: 'разовые' }).click();
await p.waitForTimeout(1600);
await p.getByPlaceholder('Город').fill('Львов');
await p.getByRole('button', { name: 'Найти' }).click();
await p.waitForTimeout(1800);
console.log('CITY    ', (await p.locator('main').innerText()).replace(/\n/g, ' | ').slice(0, 200));
await b.close();
